### ISSUE TITLE
Stuck at boot with 15.9.1

### ISSUE THREAD

**Issue by suloku** [chiteroman/PlayIntegrityFix#275]
After updating module to 15.9.1 and reboot device is stuck in boot screen. Downgrade to 15.9 solves this.

Device: Pocophone F5 (marble)
OS: hyperOS  1.0.2.0.UMRMIXM (stock + unlocked bootloader)
Magisk: v26.4 (patched boot image with 27.0 doesn't grant root access for some reason)

**Comment by 00raq00** [comment]
Confirm, Xiaomi 13t pro with android 14 same issue

**Comment by chiteroman** [comment]
v15.9.2 should fix this, can you check pls ?

**Comment by 00raq00** [comment]
> v15.9.2 should fix this, can you check pls ?

Same problem 😒 I had to rollback to 15.9 😉

**Comment by knasiotis** [comment]
15.9.2 does not fix the issue

**Comment by 00raq00** [comment]
> v15.9.2 should fix this, can you check pls ?

Does your module log anything to file? If so I can share errors from log.

**Comment by Hot12345** [comment]
> v15.9.2 should fix this, can you check pls ?

Having the same issue on Xiaomi 13 Pro. 15.9.2 does not fix the issue.

**Comment by Hot12345** [comment]
Version Version v15.9.1 won't let me boot into the stock ROM.
Testing version v15.9.

**Comment by Hot12345** [comment]
> After updating module to 15.9.1 and reboot device is stuck in boot screen. Downgrade to 15.9 solves this.
> 
> Device: Pocophone F5 (marble) OS: hyperOS 1.0.2.0.UMRMIXM (stock + unlocked bootloader) Magisk: v26.4 (patched boot image with 27.0 doesn't grant root access for some reason)

Phone booted in to the ROM. So 15.9.3 is working. While 15.9.2 & .1 is stuck at the bootloader/logo.

**Comment by knasiotis** [comment]
15.9.3 same issue

**Comment by 00raq00** [comment]
> v15.9.2 should fix this, can you check pls ?

15.9.3 fixed my problem

**Comment by suloku** [comment]
15.9.3 working here, didn't test 15.9.2 though.

**Comment by lpetflo** [comment]
For me (Mi 11 Ultra with Miui 14)  15.9.3 first seemed to work, but today my phone suddenly rebooted and is now stuck in a bootloop. After deleting the Module it booted fine. While try 15.9.4 next ...

**Comment by jere344** [comment]
For me 15.9.4 cause bootloop. Downgrade to 15.8 works.

Device: Pocophone F5 (marble)
OS: xiaomi.eu V14.0.27.0
Magisk: v27
