### ISSUE TITLE
Hi I am using PIF and before it was passing the verification but now it returns this error

### ISSUE THREAD

**Issue by rompelhd** [chiteroman/PlayIntegrityFix#429]
![IMG_20240919_232123.jpg](https://github.com/user-attachments/assets/d9e8da6d-e229-4923-a83a-637dea4e3be2)

**Comment by rompelhd** [comment]
![Screenshot_2024-09-19-23-29-19-35_c0de983bebb3f2e02853183d8c0bb272.jpg](https://github.com/user-attachments/assets/a1e9e27c-d260-4726-b3b0-e35c6cdc5e35)

I have installed the latest version in magisk

**Comment by SergeyRim** [comment]
I have the same issue since yesterday on my Xiaomi 13 with xiaomi.eu) and latest integrity fix.

**Comment by Lonelysoulman** [comment]
same here.
play integrity check fails with api error 17
and safetynet check fails with signature validation.

what can i do?

**Comment by chiteroman** [comment]
Are you using a custom ROM ?

**Comment by bphd** [comment]
> Are you using a custom ROM ?

The killing question 

Anyway I personally resolved that by reinstalling user/system gsf/gms/vending and now I'm stuck at BASIC_INTEGRITY, dunno how to get DEVICE_INTEGRITY

**Comment by rompelhd** [comment]
> Are you using a custom ROM ?

No, I'm in oxygen os 12

**Comment by bphd** [comment]
> > Are you using a custom ROM ?
> 
> No, I'm in oxygen os 12

Lucky guy, you'll get support

**Comment by Lonelysoulman** [comment]
> Are you using a custom ROM ?

yes, beyond rom 4.6 for galaxy S20.

**Comment by bphd** [comment]
> > Are you using a custom ROM ?
> 
> yes, beyond rom 4.6 for galaxy S20.

Not so lucky guy, CROM are deemed "weird" in their behavior toward Integrity and don't really get support

**Comment by Lonelysoulman** [comment]
> > > Are you using a custom ROM ?
> > 
> > 
> > yes, beyond rom 4.6 for galaxy S20.
> 
> Not so lucky guy, CROM are deemed "weird" in their behavior toward Integrity and don't really get support

well, it seems that it is no problem with the rom, since others seem to have the same error. it always worked it the past

**Comment by bphd** [comment]
> > > > Are you using a custom ROM ?
> > > 
> > > 
> > > yes, beyond rom 4.6 for galaxy S20.
> > 
> > 
> > Not so lucky guy, CROM are deemed "weird" in their behavior toward Integrity and don't really get support
> 
> well, it seems that it is no problem with the rom, since others seem to have the same error. it always worked it the past

50% of the time yeah it's the software, but 50% of other time it's the CROM, and maintainer don't want to take time to identify the culprit so they relegate per default the charge upstream. Thing is that it's not their work, they maintain a CROM, not all what was ever produced downstream... So it's complicated

Personally I would love everybody to do their maximum to identify clearly root cause, and THEN redirect to the real culprit that would have capacity to do something. For an effectively resolved problem

**Comment by NCLnclNCL** [comment]
Download blocker to enable all service and activity of gms

**Comment by Lonelysoulman** [comment]
> Download blocker to enable all service and activity of gms

what exactly should i download?

**Comment by NCLnclNCL** [comment]
> > Download blocker to enable all service and activity of gms
> 
> what exactly should i download?

https://github.com/lihenggui/blocker

**Comment by bphd** [comment]
> Download blocker to enable all service and activity of gms

Isn't blocker a firewall? How it'll permit things instead of denying?

**Comment by bphd** [comment]
> > > Download blocker to enable all service and activity of gms
> > 
> > 
> > what exactly should i download?
> 
> https://github.com/lihenggui/blocker

>> The foss version eliminates [...] GMS

**Comment by SergeyRim** [comment]
I;m google for a long of time, but still can;t find a solution. I have already try uninstall play market updates, clear cache and data for play market, clear cache/dalvik cache with no luck...

**Comment by NCLnclNCL** [comment]
> > Download blocker to enable all service and activity of gms
> 
> Isn't blocker a firewall? How it'll permit things instead of denying? Could you detail very precisely what has to be done in Blocker?
> 
> And... Aren't you a peptide? https://github.com/search?q=NCLnclNCL+&type=code
I am root phone user
Because there may be some modules you installed before that have blocked some important gms components, just turn them back on.

**Comment by bphd** [comment]
> > > Download blocker to enable all service and activity of gms
> > 
> > 
> > Isn't blocker a firewall? How it'll permit things instead of denying? Could you detail very precisely what has to be done in Blocker?
> > And... Aren't you a peptide? https://github.com/search?q=NCLnclNCL+&type=code
> > I am root phone user
> > Because there may be some modules you installed before that have blocked some important gms components, just turn them back on.

@NCLnclNCL  Modules only overlays when activated. Here they either are deactivated, either totally uninstalled, because I tried everything I know, including uninstalling every modules

And that doesn't reply about how to use precisely Blocker here to get a result

**Comment by rompelhd** [comment]
I just corrected the problem and I had disabled certain gsm services.![Screenshot_2024-09-23-20-55-29-21_c164fb607f41c6d3a88bed2bf1a99c07.jpg](https://github.com/user-attachments/assets/010de7d3-bd4c-419b-9a89-049af4e0cfc4)

**Comment by bphd** [comment]
> I just corrected the problem and I had disabled certain gsm services.

You can't just say "the problem" and "certain". You have to state precisely where "the problem" was, and what you did precisely, what is "certain"?

**Comment by NCLnclNCL** [comment]
> > I just corrected the problem and I had disabled certain gsm services.
> 
> @rompelhd You can't just say "the problem" and "certain". You have to state precisely where "the problem" was, and what you did precisely, what is "certain"?

You just need to find the module that disables some important components of gms, then you use blocker to enable all activities of gms, finding out which one is causing it is very time consuming.

**Comment by bphd** [comment]
> > > I just corrected the problem and I had disabled certain gsm services.
> > 
> > 
> > @rompelhd You can't just say "the problem" and "certain". You have to state precisely where "the problem" was, and what you did precisely, what is "certain"?
> 
> You just need to find and remove the module that disables some important components of gms, then you use blocker to enable all activities of gms, finding out which one is causing it is very time consuming.

Systemless module? I uninstalled them all to be sure and it's still the same thing, so don't even need to do cross tests
Even if you approve every network request with Blocker, some are impossible to activate and some deactivate really quick, so they're like deactivated in fact

**Comment by SergeyRim** [comment]
There is no anything about modules. The fix is simple: find Google Play services, uninstall it's updates and clear it's data. After this, upgrade play services to latest version again (you can do it from play store). Issues will be fixed. But will have to re-add all your wallet cards again.

**Comment by bphd** [comment]
> There is no anything about modules. 

What?

The fix is simple: 

> find Google Play services

com.google.android.gms?


> upgrade play services

com.google.android.gms?

> Issues will be fixed

I multiple times uninstalled all those google applications and re installed them, particularly when experiencing errors that leads to no verdict. But that basically only returns me to BASIC_INTEGRITY, no DEVICE


> I personally "resolved" that by reinstalling user/system gsf/gms/vending

https://github.com/chiteroman/PlayIntegrityFix/issues/429#issuecomment-2365328969

**Comment by bphd** [comment]
Idk if I still experiencing the error, haven't checked logs, but by deactivating `persist.sys.pixelprops.gapps` `persist.sys.pixelprops.gms` properties and resintalling vending/gsf/gms and spoofing build and provider (and btw using that module, or Osm0sis one when that one bother me) I achieve device integrity. I have difficulties achieving strong integrity but it's probably because my CROM throw `UnsupportedOperationException()` when DroidGuard ask for certificate chain, have to figure out how to patch from MagiSK, or LSP, or by replacing files
